### ISSUE TITLE
Not compatible with your version of node/npm: @appland/appmap-agent-js@13.9.1

### ISSUE THREAD

**Issue by Feuer-sturm** [ioBroker/ioBroker.device-manager#42]
**Describe the bug**  
During testing of js-controller 6 alpha this issue raised.
Nodejs20 was installed just before testing js-controller 6

**To Reproduce**  
Install js-controller 6 alpha

```
proxmox@ioBrokerTestsystem:~$ iob stop
proxmox@ioBrokerTestsystem:~$ cd /opt/iobroker/
proxmox@ioBrokerTestsystem:/opt/iobroker$ npm i iobroker.js-controller@next --omit=dev
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @appland/appmap-agent-js@13.9.1
npm ERR! notsup Not compatible with your version of node/npm: @appland/appmap-agent-js@13.9.1
npm ERR! notsup Required: {"node":"14.x.x || 16.x.x || 17.x.x || 18.x.x || 19.x.x"}
npm ERR! notsup Actual:   {"npm":"10.5.2","node":"v20.13.1"}

npm ERR! A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-05-22T11_53_14_435Z-debug-0.log
```

```
proxmox@ioBrokerTestsystem:/opt/iobroker$ npm ls @appland/appmap-agent-js
iobroker.inst@2.0.3 /opt/iobroker
`-- iobroker.device-manager@0.0.3
  `-- @appland/appmap-agent-js@13.9.1
 
```

**Expected behavior**  

**Screenshots & Logfiles**  
Discussion in forum with foxriver: https://forum.iobroker.net/topic/74822/alpha-test-js-controller-kiera-v6-0/12

**Versions:**  
 - Adapter version: 0.0.3
 - JS-Controller version: 5.0.19
*** NodeJS-Installation ***
/usr/bin/nodejs         v20.13.1
/usr/bin/node           v20.13.1
/usr/bin/npm            10.5.2
/usr/bin/npx            10.5.2
/usr/bin/corepack       0.28.0

**Comment by Jey-Cee** [comment]
Looks like it's a corpse.
